#include "Dictionary.h"
#include "Pair.h"
#include "List.h"
#include <iostream>
#include <string>
#include <stdexcept>

static int g_pass = 0;
static int g_fail = 0;
static void check(bool cond, const std::string& name) {
    if (cond) { std::cout << "  [PASS] " << name << "\n"; ++g_pass; }
    else      { std::cout << "  [FAIL] " << name << "\n"; ++g_fail; }
}

static std::string toStr(int x)                { return std::to_string(x); }
static std::string toStr(const std::string& x) { return x; }

template <typename T>
static std::string listToString(List<T>& l) {
    std::string s;
    l.traverse([&](T& x) { s += toStr(x); s += " "; });
    return s;
}

static void testPair() {
    std::cout << "1. Pair<Key,Value> ordering via defaulted <=>\n";
    Pair<std::string, int> a{"apple", 1};
    Pair<std::string, int> b{"banana", 2};
    Pair<std::string, int> a2{"apple", 1};
    check(a < b,             "pair orders by key (apple < banana)");
    check(a == a2,           "pairs with same key and value compare equal");
    check(b > a,             "reverse comparison generated by <=>");
    check(a.first == "apple" && a.second == 1, "first/second fields accessible");
}

static void testInsertAndOrder() {
    std::cout << "2. insert() keeps pairs sorted ascending by key\n";
    Dictionary<std::string, int> d;
    check(d.isEmpty(),        "new dictionary is empty");
    check(d.size() == 0,      "new dictionary has size 0");

    d.insert("cherry", 3);
    d.insert("apple", 1);
    d.insert("date", 4);
    d.insert("banana", 2);

    check(!d.isEmpty(),       "dictionary not empty after inserts");
    check(d.size() == 4,      "size counts the four inserted pairs");
    check(listToString(d.keys())   == "apple banana cherry date ",
          "keys() come back in ascending sorted order");
    check(listToString(d.values()) == "1 2 3 4 ",
          "values() are ordered to match keys()");
}

static void testLookup() {
    std::cout << "3. at() and contains()\n";
    Dictionary<std::string, int> d;
    d.insert("one", 1);
    d.insert("two", 2);

    check(d.contains("one"),   "contains() finds a present key");
    check(!d.contains("nope"), "contains() rejects an absent key");
    check(d.at("two") == 2,    "at() returns the stored value");

    bool threw = false;
    try { d.at("missing"); }
    catch (const std::out_of_range&) { threw = true; }
    check(threw, "at() throws std::out_of_range for a missing key");
}

static void testSubscript() {
    std::cout << "4. operator[] reads, writes, and inserts-on-access\n";
    Dictionary<std::string, int> d;

    d["x"] = 10;
    d["y"] = 20;
    int vx = d["x"];
    check(vx == 10,          "operator[] write-through then read returns value");
    check(d.size() == 2,     "two keys after two subscript assignments");

    d["x"] = 99;
    int vx2 = d["x"];
    check(vx2 == 99,         "operator[] overwrites an existing key's value");
    check(d.size() == 2,     "overwrite does not change size");

    int fresh = d["z"];
    check(fresh == 0,        "operator[] on absent key yields default Value{}");
    check(d.size() == 3,     "operator[] on absent key inserts a new pair");
    check(d.contains("z"),   "the default-inserted key is now present");
}

static void testInsertUpsert() {
    std::cout << "5. insert() updates the value of an existing key\n";
    Dictionary<std::string, int> d;
    d.insert("k", 1);
    d.insert("k", 42);
    check(d.size() == 1,     "re-inserting a key does not add a duplicate");
    check(d.at("k") == 42,   "re-inserting a key replaces its value");

    d.insert(Pair<std::string, int>{"p", 7});
    check(d.at("p") == 7,    "insert(Pair) stores the pair");
}

static void testErase() {
    std::cout << "6. erase() and clear()\n";
    Dictionary<std::string, int> d;
    d.insert("a", 1);
    d.insert("b", 2);
    d.insert("c", 3);

    d.erase("b");
    check(d.size() == 2,      "erase() drops the size");
    check(!d.contains("b"),   "erased key is gone");
    check(listToString(d.keys()) == "a c ", "erase() preserves order of the rest");

    d.erase("does-not-exist");
    check(d.size() == 2,       "erasing an absent key is a no-op");

    d.clear();
    check(d.isEmpty(),         "clear() empties the dictionary");
    check(d.size() == 0,       "size is 0 after clear()");
}

static void testRuleOfFive() {
    std::cout << "7. Rule of Five: copies are independent, moves transfer\n";
    Dictionary<int, std::string> a;
    a.insert(1, "one");
    a.insert(2, "two");

    Dictionary<int, std::string> b(a);
    b.insert(3, "three");
    check(a.size() == 2 && b.size() == 3,
          "copy constructor produces an independent dictionary");

    Dictionary<int, std::string> c;
    c = a;
    a.erase(1);
    check(c.size() == 2 && c.contains(1),
          "copy assignment is independent of later changes to the source");

    Dictionary<int, std::string> d(std::move(b));
    check(d.size() == 3 && d.at(3) == "three",
          "move constructor transfers contents");

    Dictionary<int, std::string> e;
    e = std::move(d);
    check(e.size() == 3 && e.at(2) == "two",
          "move assignment transfers contents");
}

static void testIntKeys() {
    std::cout << "8. Ascending order holds for numeric keys\n";
    Dictionary<int, std::string> d;
    d.insert(50, "z");
    d.insert(10, "a");
    d.insert(30, "m");
    d.insert(20, "b");
    check(listToString(d.keys()) == "10 20 30 50 ",
          "integer keys traverse in ascending order");
    check(listToString(d.values()) == "a b m z ",
          "values follow their keys");
}

int main() {
    std::cout << "- Dictionary / Pair test driver -\n";
    testPair();
    testInsertAndOrder();
    testLookup();
    testSubscript();
    testInsertUpsert();
    testErase();
    testRuleOfFive();
    testIntKeys();
    std::cout << "----------------------------------------------------------------\n";
    std::cout << "Results: " << g_pass << " passed, " << g_fail << " failed.\n";
    return g_fail == 0 ? 0 : 1;
}
